name: Publish intrabus to PyPI on tag

on:
  push:
    tags: ['v*']            # v0.1.0, v1.0.0-rc1, etc.
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry & Twine
        run: |
          python -m pip install --upgrade pip
          pip install poetry twine

      - name: Build wheel + sdist
        run: |
          poetry install --no-interaction --only main
          poetry build

      - name: Upload to PyPI
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          twine upload --skip-existing dist/*