name: CI

on:
  push:
    branches: ["main"]
    tags: 
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry & Twine
        run: |
          python -m pip install --upgrade pip
          pip install poetry twine

      - name: Build package
        run: |
          poetry install --no-interaction --only main
          poetry build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          twine upload --skip-existing dist/*